# Site setings
name: 'James Milton'
description: 'James Milton is a Designer and Creator from the U.K, currently living in Salzburg, Austria.'
# Sidebar about text
site_description: 'Welcome to my website. It features topics such as design, video, travel & code. This blog is about finding balance in life, living with purpose, having fun, and doing what you love.'
logo: '/assets/images/pages/about.jpg'
favicon: '/assets/images/favicon.ico'
baseurl:
production_url: https://jamesmilton.me/
disqus: 'james-milton'
mailchimp_url:
# Add your GA Tracking Id
ga_analytics: 'UA-47742897-8'

# Contact form setings
email: james.milton@me.com
contact_page_description: "Shoot me a message!"
thankyou_page_description: "Your message has been successfully sent. I will contact you very soon!"

# Social links
twitter:
facebook:
github:
codepen:
dribbble:
medium:
instagram: 'james.jpg'
pinterest:
linkedin: 'jmltn'

# Navigation
navigation:
  - text: Home
    url: /
  - text: Portfolio
    url: /portfolio/
  - text: Contact Me
    url: /contact/

# Required Plugins
plugins:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap

# Pagination
paginate: 6
paginate_path: "/portfolio/page:num/"

# Permalinks
permalink: /:title

# Other
markdown: kramdown

# Sass
sass:
  sass_dir: _sass
  style: compressed

# Collections
collections:
  authors:
    title: Authors Page
    output: true
  blog_tags:
    title: Tags Page
    output: true

# Defaults
defaults:
- scope:
    path: ''
    type: authors
  values:
    permalink: "/author/:title/"
    layout: author
- scope:
    path: ''
    type: blog_tags
  values:
    permalink: "/tag/:title/"
    layout: tag

# SEO
title: 'James Milton''s Portfolio'
tagline: 'James Milton is a Designer and Creator from the U.K, currently living in Salzburg, Austria.'
url: jamesmilton.me
author: james

social:
  name: James Milton
  links:
    - https://twitter.com/jmltn
    - https://www.facebook.com/jmltn.1
    - https://www.linkedin.com/in/jmltn
    - https://github.com/jmltn
    - https://instagram.com/james.

github: [metadata]
